Fix *Possible* Final Error
👷Fixed The Only Error On - Compile. ( Not Confirmed )

✳️ Note The last error is:
error: conversion to non-scalar type requested
This Solution came to my head seeing how malloc returns void* but is used on any pointer of any type.